/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/front/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Front Search */
        get: operations["front_front_api_api_front_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/front/api/search/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Front Search Home */
        get: operations["front_front_api_api_front_search_home"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/front/api/search/diocese/{diocese_uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Front Search Diocese */
        get: operations["front_front_api_api_front_search_diocese"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/front/api/church/{church_uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Front Church Details */
        get: operations["front_front_api_api_front_church_details"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/front/api/autocomplete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Front Autocomplete */
        get: operations["front_front_api_api_front_autocomplete"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/front/api/autocomplete/hits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Front Post Autocomplete Hit */
        post: operations["front_front_api_api_front_post_autocomplete_hit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/front/api/dioceses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Front Get Dioceses */
        get: operations["front_front_api_api_front_get_dioceses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/front/api/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Front Post Reports */
        post: operations["front_front_api_api_front_post_reports"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/front/api/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Front Post Images */
        post: operations["front_front_api_api_front_post_images"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AggregationOut */
        AggregationOut: {
            /**
             * Type
             * @enum {string}
             */
            type: "diocese" | "parish" | "municipality";
            /** Name */
            name: string;
            /** Church Count */
            church_count: number;
            /** Church With Event Count */
            church_with_event_count: number;
            /** Centroid Latitude */
            centroid_latitude: number;
            /** Centroid Longitude */
            centroid_longitude: number;
            /** Min Latitude */
            min_latitude: number;
            /** Max Latitude */
            max_latitude: number;
            /** Min Longitude */
            min_longitude: number;
            /** Max Longitude */
            max_longitude: number;
        };
        /** ChurchOut */
        ChurchOut: {
            /**
             * Uuid
             * Format: uuid
             */
            uuid: string;
            /** Name */
            name: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Address */
            address: string | null;
            /** Zipcode */
            zipcode: string | null;
            /** City */
            city: string | null;
            /** Events */
            events: components["schemas"]["EventOut"][];
        };
        /** EventOut */
        EventOut: {
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /** End */
            end: string | null;
            /** Schedules Indices */
            schedules_indices: number[];
            /** Source Has Been Moderated */
            source_has_been_moderated: boolean;
        };
        /** SearchResultOut */
        SearchResultOut: {
            /** Churches */
            churches: components["schemas"]["ChurchOut"][];
            /** Aggregations */
            aggregations: components["schemas"]["AggregationOut"][];
        };
        /** ErrorSchema */
        ErrorSchema: {
            /** Detail */
            detail: string;
        };
        /** ChurchDetails */
        ChurchDetails: {
            /**
             * Uuid
             * Format: uuid
             */
            uuid: string;
            /** Name */
            name: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Address */
            address: string | null;
            /** Zipcode */
            zipcode: string | null;
            /** City */
            city: string | null;
            /** Events */
            events: components["schemas"]["EventOut"][];
            website: components["schemas"]["WebsiteOut"];
            /** Schedules */
            schedules: components["schemas"]["ScheduleOut"][];
            /** Parsings */
            parsings: components["schemas"]["ParsingOut"][];
            /** Periods */
            periods: components["schemas"]["PeriodEnum"][];
        };
        /**
         * FeedbackTypeEnum
         * @enum {string}
         */
        FeedbackTypeEnum: "good" | "error" | "comment";
        /** ParsingOut */
        ParsingOut: {
            /**
             * Uuid
             * Format: uuid
             */
            uuid: string;
            /** Scraping Url */
            scraping_url: string | null;
            /** Image Url */
            image_url: string | null;
        };
        /**
         * PeriodEnum
         * @enum {string}
         */
        PeriodEnum: "summer" | "winter" | "advent" | "lent" | "solemnities" | "holy_week" | "school_holidays";
        /** ReportOut */
        ReportOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            feedback_type: components["schemas"]["FeedbackTypeEnum"];
            /** Comment */
            comment: string | null;
            /** Sub Reports */
            sub_reports: components["schemas"]["ReportOut"][];
        };
        /** ScheduleOut */
        ScheduleOut: {
            /** Explanation */
            explanation: string;
            /** Sources */
            sources: components["schemas"]["SourceOut"][];
        };
        /** SourceOut */
        SourceOut: {
            source_type: components["schemas"]["SourceTypeEnum"];
            /** Parsing Uuid */
            parsing_uuid: string | null;
        };
        /**
         * SourceTypeEnum
         * @enum {string}
         */
        SourceTypeEnum: "parsing" | "oclocher";
        /** WebsiteOut */
        WebsiteOut: {
            /**
             * Uuid
             * Format: uuid
             */
            uuid: string;
            /** Name */
            name: string;
            /** Home Url */
            home_url: string;
            /** Reports */
            reports: components["schemas"]["ReportOut"][];
        };
        /** AutocompleteItem */
        AutocompleteItem: {
            /** Type */
            type: string;
            /** Name */
            name: string;
            /** Context */
            context: string | null;
            /** Url */
            url: string;
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
            /** Uuid */
            uuid?: string | null;
        };
        /** AutocompleteHitIn */
        AutocompleteHitIn: {
            /** Query */
            query: string;
            /** Latitude */
            latitude: number | null;
            /** Longitude */
            longitude: number | null;
            /** Rank */
            rank: number;
            item: components["schemas"]["AutocompleteItem"];
        };
        /** DioceseOut */
        DioceseOut: {
            /**
             * Uuid
             * Format: uuid
             */
            uuid: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Min Latitude */
            min_latitude: number;
            /** Max Latitude */
            max_latitude: number;
            /** Min Longitude */
            min_longitude: number;
            /** Max Longitude */
            max_longitude: number;
        };
        /**
         * ErrorTypeEnum
         * @enum {string}
         */
        ErrorTypeEnum: "outdated" | "churches" | "paragraphs" | "schedules";
        /** ReportIn */
        ReportIn: {
            /**
             * Website Uuid
             * Format: uuid
             */
            website_uuid: string;
            feedback_type: components["schemas"]["FeedbackTypeEnum"];
            error_type?: components["schemas"]["ErrorTypeEnum"] | null;
            /** Comment */
            comment?: string | null;
        };
        /** ImageOut */
        ImageOut: {
            /**
             * Image Uuid
             * Format: uuid
             */
            image_uuid: string;
            /** Public Url */
            public_url: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    front_front_api_api_front_search: {
        parameters: {
            query?: {
                latitude?: number | null;
                longitude?: number | null;
                min_lat?: number | null;
                min_lng?: number | null;
                max_lat?: number | null;
                max_lng?: number | null;
                date_filter?: string | null;
                hour_min?: number;
                hour_max?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResultOut"];
                };
            };
        };
    };
    front_front_api_api_front_search_home: {
        parameters: {
            query: {
                min_lat: number;
                min_lng: number;
                max_lat: number;
                max_lng: number;
                date_filter?: string | null;
                hour_min?: number;
                hour_max?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResultOut"];
                };
            };
        };
    };
    front_front_api_api_front_search_diocese: {
        parameters: {
            query?: {
                date_filter?: string | null;
                hour_min?: number;
                hour_max?: number;
            };
            header?: never;
            path: {
                diocese_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResultOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
        };
    };
    front_front_api_api_front_church_details: {
        parameters: {
            query?: {
                date_filter?: string | null;
                hour_min?: number;
                hour_max?: number;
            };
            header?: never;
            path: {
                church_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChurchDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
        };
    };
    front_front_api_api_front_autocomplete: {
        parameters: {
            query: {
                query: string;
                latitude?: number | null;
                longitude?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutocompleteItem"][];
                };
            };
        };
    };
    front_front_api_api_front_post_autocomplete_hit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutocompleteHitIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutocompleteHitIn"];
                };
            };
        };
    };
    front_front_api_api_front_get_dioceses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DioceseOut"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
        };
    };
    front_front_api_api_front_post_reports: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
        };
    };
    front_front_api_api_front_post_images: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Website Uuid
                     * Format: uuid
                     */
                    website_uuid: string;
                    /** Comment */
                    comment?: string | null;
                    /**
                     * Document
                     * Format: binary
                     */
                    document: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
        };
    };
}
